module.exports = {
  ".slds-icon-waffle": require('./locator.nXZrImvQ4rlzYX3Z.json'),
  "Search_apps_and_items...": require('./locator.pLqD2FNxO7c4WsXa.json'),
  "Sale": require('./locator.l49f7RgwL3Lgiu2X.json'),
  "eNMmMht33jIWYqmv": require('./locator.eNMmMht33jIWYqmv.json'),
  "Enter_name": require('./locator.iWrZJEK7CKUKxDFd.json'),
  "Primary_action": require('./locator.cWRHHkyG8028QpxV.json'),
  "Home": require('./locator.bmKk4Dyy5Zmm8hMY.json'),
  "[aria-invalid='false']": require('./locator.RUxpqOPFRVqI5IyX.json'),
  ".slds-p-around_medium_>_lightning-b": require('./locator.Huwrg7ApiTTjzjjS.json'),
  "close_Close_List_of_search_test_obj": require('./locator.vSgQvLJQn1nkXw49.json'),
  "Product_Name": require('./locator.zzVOfDuFscWOQP5A.json'),
  "Cancel": require('./locator.aQf5Lcmb2Kzx95ZB.json'),
  "TestCustomObjects": require('./locator.Em0PW0aZNRuYMFNF.json'),
  "Search_this_list...": require('./locator.tiLO2f94nWcSwWcz.json'),
  ".listDisplays_.slds-icon_container_": require('./locator.bZdI5JjwLuvtMG0u.json'),
  "Delete": require('./locator.MTLGEHDKerlRPDLe.json'),
  "Delete_TestCustomObject_Close_this_": require('./locator.P0YgXIl5Tftq9UPG.json'),
  "Are_you_sure_you_want_to_delete_thi": require('./locator.CWMWO7BnMGnO9lpl.json'),
  "[data-aura-class='uiButton--default": require('./locator.K6xSpl5Fd0GLBkex.json'),
  "[data-id='0Qk3F0000000tfRSAQ']_.sld": require('./locator.aF5CD8ifrVOGLnY2.json'),
  "Sales": require('./locator.BGZ5QhQles316G4A.json'),
  "[data-id='0Qk8a000000mtBuCAI']_.sld": require('./locator.6dYEzmHbWXSoldCC.json'),
  "Test_Custom_Object": require('./locator.uR3nWYwYAzSfS0xm.json'),
  ".slds-form-element_edit_.test-id__f": require('./locator.ZlLiH29z5swbr0ro.json'),
  "[id='oneHeader']_.uiImage": require('./locator.vBymhAl3R4eXwCGF.json'),
  "Log_Out": require('./locator.AV6fnMdMfPmTdYrB.json'),
};